### ISSUE TITLE
Flexbot confidential

### ISSUE THREAD

**Issue by ava5627** [luizbgomide/EclipsePhase2e-ptbr#41]
Would it be ok if I made a pull request adding the flexbot confidential book

**Comment by luizbgomide** [comment]
Hello Ava,
If you got how I organize my .MD files, sure thing. I just ask that you
send the PDF to me ***@***.***) so that I can verify it before
accepting.

Em ter., 30 de jul. de 2024 17:15, Ava Harris ***@***.***>
escreveu:

**Comment by ava5627** [comment]
Sure, Github filtered out your email but I'll attach it here

[Flexbot Confidential.pdf](https://github.com/user-attachments/files/16434889/Flexbot.Confidential.pdf)

**Comment by luizbgomide** [comment]
Done, take a look and tell me what you think of it :)
