### ISSUE TITLE
Flexbot confidential: Flexbot modules not accesible

### ISSUE THREAD

**Issue by ava5627** [luizbgomide/EclipsePhase2e-ptbr#44]
Incorrect indentation here
https://github.com/luizbgomide/EclipsePhase2e-ptbr/blob/538c47de4db70a8a03b3f648bb8365f5744dfb43/src/SUPP/03-FC/00-flexbot-confidential.md?plain=1#L80-L98

Missing here
https://github.com/luizbgomide/EclipsePhase2e-ptbr/blob/538c47de4db70a8a03b3f648bb8365f5744dfb43/src/SUMMARY.md?plain=1#L300-L301

**Comment by luizbgomide** [comment]
Should be fixed now :)
