### ISSUE TITLE
Many Character Options MRG lore bits are broken

### ISSUE THREAD

**Issue by Ashran31** [luizbgomide/EclipsePhase2e-ptbr#45]
The appeareance of a colon [:] breaks the formatting of the lore bits, such as for example in the scurrier entry. Ive noticed it on multiple entries.
![imagen](https://github.com/user-attachments/assets/ad13a3ec-5d51-479d-9245-b74b291546f4)

**Comment by luizbgomide** [comment]
Good catch! I think I fixed them all, let me know if you found anything else.
